
services:

    mlflow-db:
        container_name: mlflow-db
        image: postgres:14-alpine
        restart: always
        env_file:
          - ./.env
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - APP_DB_USER=${APP_DB_USER}
          - APP_DB_PASSWORD=${APP_DB_PASSWORD}
        volumes:
          - db-volume:/var/lib/postgresql/data
          - ./database/backups:/backups:ro
          - ./database/config/pga_hba.conf:/postgres_data/postgresql/data/pg_hba.conf
          - ./database/config/postgresql.conf:/postgres_data/postgresql/data/postgresql.conf
          - ./database/init:/docker-entrypoint-initdb.d/
        ports:
          - 5432:5432
        networks:
          api-network:

volumes:
  db-volume:

networks:
  api-network:
    driver: bridge