
name: format + lint

on:
  push:
    paths:
      - 'chickenstats/**.py'
      - 'tests/**.py'
  workflow_call:

permissions:
  contents: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install black

    - name: Lint with Ruff
      run: |
        ruff check chickenstats
        ruff check tests
    - name: Format with Black
      run: |
        black chickenstats
        black tests
        
